ktor:
    application:
        modules:
            - com.aimhigh.app.ApplicationKt.module
    deployment:
        port: 8080

dwello:
    mongo:
        uri: ${MONGODB_CONNECTION_STRING}
        db: ${DATABASE_NAME}